# fly.toml app configuration file generated for create-fly-backend on 2025-04-09T22:13:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'create-fly-backend'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'create_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
